PROGRAM        = blinky

# these values are set automatically
# uncomment and change them to override defauls
#
# FLASH_SIZE     = 8m
# FLASH_MODE     = dio
# ESPBAUD        = 115200
# ESPPORT        = /dev/ttyUSB0

LIBS           = gcc
SDK_LIBS       = main net80211 lwip phy pp wpa

include $(ESP_OPEN_SDK)/common.mk
